### ISSUE TITLE
Inject function type

### ISSUE THREAD

**Issue by Adambl4** [kohesive/injekt#35]
how to achive something like this:
`val function: (Int) -> Int = Injekt.get()`

**Comment by apatrida** [comment]
This is difficult because of not having great ways to differentiate the internal types without looking at implementation details (unsafe?).  Maybe with type definitions coming in the future if available to reflection it could be a way to do this safely.  I'll see if I come up with something in the meantime.

**Comment by apatrida** [comment]
The type above is compiled to:

```
kotlin.jvm.functions.Function1<? super java.lang.Integer, ? extends java.lang.Integer>" 
```

which as `Type` is a `ParameterizedType` 

The factory held in memory is:

```
Function0<kotlin.jvm.functions.Function1<? super java.lang.Integer, ? extends java.lang.Integer>>
```

So all of that is dangerous to Injekt since we cannot differentiate really between similar functions which could be in abundance in an application.  

Type Alises described as:

> Type aliases will allow to assign a short name to a type (for example, a function type, or a generic type with a long signature):
typealias MouseEventHandler = (MouseEvent) -> Unit

would be useful IF available at reflection time.

One approach that might work now is to use an annotation and naming the function with an alias.  But that would only be valid for functions that were declared in a way that an annotation could target them.

**Comment by apatrida** [comment]
So you can use the way mentioned above in the first comment, or you can make it safer by wrapping the function with a class that you can specify when injecting, and if you add the invoke function to that class you can make it feel very natural:

```
    class Int1Action(val function: (Int) -> Int) {
        operator fun invoke(i: Int): Int = function(i)
    }

    @Test fun testInjectFunctionWrapper() {
        Injekt.addSingletonFactory {
            val function: (Int) -> Int = { value -> value + 20 }
            Int1Action(function)
        }

        val action: Int1Action = Injekt.get()
        assertEquals(22, action(2))
    }
```

**Comment by apatrida** [comment]
Added to Stackoverflow as  http://stackoverflow.com/questions/37550923
